### ISSUE TITLE
Setup AWS Virtual Private Cloud (VPC)

### ISSUE THREAD

**Issue by jjd90** [jjd90/gitlegion#2]
An AWS VPC allows every organization to setup one or more networks inside of AWS. You should be given a default VPC with a given subnet (Usually 172.31.0.0/16). You will need to 
break these networks into public and private subnetworks to allow services in AWS to function properly.Design your network so that there are the following subnets:

●    3 public subnets in 3 different availability zones (AZ) with at least 1024 available IP addresses per subnet.

●    3 private subnets in 3 different availability zones (AZ) with at least 4096 available IP addresses per subnet.

●    1 route table for the public subnets

●    1 route table for the private subnets

●    1 Internet Gateway (IG) attached to the default route of the public subnet routing table

**Comment by ghost** [comment]
Almost done. Need to attach an internet gateway to the public subnet routing table. (10/7)

**Comment by ghost** [comment]
Still will keep this open. I want to make sure that any possible configurations that can help the EC2 are taken care of from the VPC or if there are any errors from my end that are affecting the EC2. (10/9)
