### ISSUE TITLE
Generate TLS Certificates

### ISSUE THREAD

**Issue by jjd90** [jjd90/gitlegion#5]
It is important to protect users to any website by encrypting traffic to and from it. We do this using Transport Layer Security (TLS) certificates. For a long time, buying a TLS certificate was very expensive but recent efforts have made these certificates free. One such project that has 
helped this is called Let's Encrypt. Let's Encrypt will allow the owner of a domain to verify ownership and be able to get a TLS certificate for free.You must generate a set of security certificates for your domain that will work for each of the DNS addresses mentioned in the section "Setup your Domain". A single certificate should be used for all of the addresses.The private key of your TLS certificate should be kept secret and not shared with anyone outside of your group to ensure that your users are protected. You must determine a safe and effective way to store and protect your certificates while also making them available to your instance to use. You can look at other AWS services such as the Secret Store to help with this.

**Comment by yousefjnm** [comment]
From AWS Certificate Manger, I requested a public certificate and after entering our domain name, I was able to validate that we own this domain name using "DNS validation" and followed the steps there. After waiting for about 30 minutes, AWS issued our certificate.
